BestStore/Auth/urls.py
from django.urls import path
from .views import user_login
from .views import logout_view
from .views import register_user
from .views import verify_user_email
from .views import render_login_form
from .views import render_register_form
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('api/user/login/', user_login, name='user_login'),
    path('login/', render_login_form, name="loginform"),
    path('api/user/register/', register_user, name='register_post'),
    path('register/', render_register_form, name='registerform'),
    path('api/user/verify/<str:token>/', verify_user_email, name='user_verify'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='Auth/password_reset.html', html_email_template_name="Auth/email_reset_template.html", subject_template_name="Auth/password_reset_subject.txt"), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='Auth/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='Auth/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='Auth/password_reset_complete.html'), name='password_reset_complete'),

]

BestStore/BestStore/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from .settings import MEDIA_ROOT, MEDIA_URL
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Products.urls')),
    path('', include('Auth.urls')),
    path('', include('User.urls')),
    path('', include('Orders.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

BestStore/Products/urls.py
from django.urls import path
from .views import (
    cart_add, cart_empty, home, product_listings, ProductDetailView,
    cart_item_remove,
    wishlist_items)

urlpatterns = [
    path('', home, name="homepage"),
    path('products/', product_listings, name="products"),
    path('products/<int:pk>/', ProductDetailView.as_view(), name="detail"),
    path('api/product/cart/add/<int:pk>/', cart_add, name='cart-add'),
    path('api/product/cart/empty/', cart_empty, name='cart-empty-all'),
    path('api/product/cart/empty/<int:pk>/', cart_empty, name='cart-empty'),
    path('api/product/cart/remove/<int:pk>/', cart_item_remove, name='cart-item-remove'),
    path('wishlist/', wishlist_items, name='wishlist'),
]

BestStore/FrontEnd/models.py
from django.db import models

# Create your models here.

BestStore/Products/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICES = (
    ('Electronic', 'Electronic'),
    ('Cloth', 'Cloth'),
    ('Kid', 'Kid'),
)

SUB_CATEGORY_CHOICES = (
    ('Mobile', 'Mobile'),
    ('TV', 'TV'),
    ('Shirt', 'Shirt'),
    ('Pant', 'Pant'),
    ('Toy', 'Toy'),
    ('Book', 'Book'),
)

COLOR_CHOICES = (
    ('Black', 'Black'),
    ('Blue', 'Blue'),
    ('Red', 'Red'),
    ('Green', 'Green'),
    ('White', 'White'),
    ('Rose Gold', 'Rose Gold'),
    ('Grey', 'Grey'),
)

PAYMENT_CHOICES = (
    ('COD', 'COD'),
    ('Credit Card', 'Credit Card'),
    ('Debit Card', 'Debit Card'),
    ('WALLET', 'WALLET'),
    ('BTC', 'BTC'),
)


class Category(models.Model):
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)

    def __str__(self):
        return self.category


class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, choices=SUB_CATEGORY_CHOICES)

    def __str__(self):
        return self.title

      
class Product(models.Model):
    merchant = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    price = models.IntegerField()
    quantity = models.IntegerField()
    added_date = models.DateTimeField(auto_now_add=True, null=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tags(models.Model):
    sub_category = models.ForeignKey(SubCategory, on_delete=models.CASCADE)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, default=1)
    size = models.CharField(max_length=20)
    color = models.CharField(max_length=20, choices=COLOR_CHOICES)
    weight = models.CharField(max_length=20)


class ProductImages(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField()


# class Orders(models.Model):
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     buyer = models.ForeignKey(User, on_delete=models.CASCADE)
#     order_date = models.DateTimeField(auto_now_add=True)
#     payment_type = models.CharField(max_length=20, choices=PAYMENT_CHOICES)
#     quantity = models.IntegerField()
#

class Wishlist(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['customer', 'item']

BestStore/FrontEnd/views.py
from django.shortcuts import render

# Create your views here.

BestStore/Products/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template.loader import render_to_string
from django.views.generic import ListView
from .models import Product, Category, SubCategory, Newsletter, Tags, Wishlist
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.detail import DetailView
from collections import OrderedDict
from BestStore.settings import PRODUCTS_PER_PAGE, \
    PAGINATION_URL, EMAIL_SUBJECT, DUMMY_EMAIL


def home(request):
    """
        This will render the homepage
        :param request: Django's HTTP Request object
        :return: Rendered homepage block to base template
    """
    featured = Product.objects.filter(is_featured=1).order_by('-modified_date')[:3]
    all_category = Category.objects.all()
    context = {'featured_products': featured, 'category': all_category}

    # Save newsletter information
    if request.method == 'POST':
        mail = request.POST.get('news_letter_email')
        try:
            user = Newsletter.objects.get(email=mail)
            context['mail_exists'] = False
        except Exception:
            user = Newsletter.objects.create(email=mail)
            user.save()
            context['Success'] = True
            plain_message = "Successfully Subscribed to our news letter!"
            html_message = render_to_string('General/newsletter.html')
            send_mail(EMAIL_SUBJECT,
                      plain_message,
                      DUMMY_EMAIL,
                      [mail],
                      html_message=html_message,
                      fail_silently=False)
        return render(request, "Products/homepage.html", context)

    return render(request, "Products/homepage.html", context)


def product_listings(request):
    """
        List products via custom pagination algorithm
        :param request: Django's HTTP Request object
        :return: Rendered product list view with pagination
    """
    search_term = ""
    filter = dict()
    filter_tags = dict()
    try:
        # Extract page parameter from page request and try to convert to int
        page = int(request.GET.get('page', 1))
    except ValueError:
        # If page argument is an alphabet this will set the page to 1
        page = 1
    # Grab all categories for filtering purposes on web page
    all_category = Category.objects.all()
    all_sub_category = SubCategory.objects.all()
    # Grab all products to paginate
    all_products = Product.objects.all()
    filter['product'] = all_products
    # Search functionality
    if 'search' in request.GET:
        filter = product_search(request)
    if 'filter_category' in request.GET or 'filter_sub_category' in request.GET:
        filters = filter_listings(request)
        if filters.get('filter_tag'):
            filter_tags = filters['filter_tag']
            filter_detail = filters['filter_detail']
            del filters['filter_detail']
            del filters['filter_tag']
        filter['product'] = Product.objects.filter(**filters)
        if filter_detail:
            product_detail = set()
            product_details = Tags.objects.filter(**filter_detail)
            for prod in product_details:
                product_detail.add(prod.product)
            filter['product'] = set(filter['product']).intersection(product_detail)
        filter['category'] = request.GET.get('filter_category')
        filter['sub_category'] = request.GET.get('filter_sub_category')
    # If no products are in database then we have nothing to show the user
    # Set appropriate values for pagination parameters
    paginator = Paginator(list(filter['product']), 6)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # Set context variable for template to use to display the products and paginated navigation

    # import pdb; pdb.set_trace()
    if not filter.get('product'):


        info = {
            'category': all_category,
            'message': "No products found!",
            'filter_tags': filter_tags,
        }
    else:
        info = {
            'category': all_category,
            'category_selected': filter.get('category'),
            'sub_category_selected': filter.get('sub_category'),
            'product': filter.get('product'),
            'products': products,
            'search_term': search_term,
            'filter_tags': filter_tags,
        }

    # Render template with context containing pagination details
    return render(request, 'Products/products.html', context=info)


def product_search(request):
    filter = dict()
    search_type = request.GET.get('search', None)
    try:
        search_type = search_type.split(' [ in ')
        search_name = search_type[0]
        search_type = search_type[1].split(' ]')[0]
        if search_type == 'Category':
            filter['category__category'] = search_name
        if search_type == 'Sub-Category':
            filter['subcategory__title'] = search_name
        filter['product'] = Product.objects.filter(**filter)
        if filter['category__category']:
            filter['category'] = search_name
        else:
            filter['sub_category'] = search_name
    except IndexError:
        search_type = 'Products'
    if search_type == 'Products':
        products = Product.objects.filter(name__icontains=search_name)
        filter['product'] = products
    return filter


# def filter_products(**filter):
#     products = set(Product.objects.all())
#     if filter.get('category'):
#         products_in_category = set(Category.objects.filter(category__icontains=filter['category'])[0].product_set.all())
#         products = products.intersection(products_in_category)
#     if filter.get('sub_category'):
#         products_in_sub_category = set(
#             SubCategory.objects.filter(title__icontains=filter['sub_category'])[0].product_set.all())
#         products = products.intersection(products_in_sub_category)
#     if filter.get('min_price_value'):
#         products_by_price = []
#         price_filter = Product.objects.filter(price__range=(filter['min_price_value'], filter['max_price_value']))
#         for i in range(0, len(price_filter)):
#             products_by_price.append(price_filter[i])
#         products = products.intersection(set(products_by_price))
#     if filter.get('min_weight_value'):
#         products_by_weight =[]
#         weight_filter = Product.objects.filter(tags__weight__range=(filter['min_weight_value'], filter['max_weight_value']))
#         for i in range(0, len(weight_filter)):
#             products_by_weight.append(weight_filter[i])
#         products = products.intersection(set(products_by_weight))
#     if filter.get('size') and filter.get('size') != 'All':
#         products_by_size = []
#         size_filter = Product.objects.filter(tags__size__icontains=filter['size'])
#         for i in range(0, len(size_filter)):
#             products_by_size.append(size_filter[i])
#         products = products.intersection(set(products_by_size))
#     if filter.get('color') and filter.get('size') != 'All':
#         products_by_color = []
#         color_filter = Product.objects.filter(tags__color__icontains=filter['color'])
#         for i in range(0, len(color_filter)):
#             products_by_color.append(color_filter[i])
#         products = products.intersection(set(products_by_color))
#     filter['product'] = products
#     return filter


def filter_listings(request):
        filter_detail = dict()
        filter = dict()
        filer_tag = []
        if request.GET.get('filter_category'):
            filter['category__category'] = request.GET.get('filter_category', None)
            filer_tag.append(filter['category__category'])
        if request.GET.get('filter_sub_category'):
            filter['subcategory__title'] = request.GET.get('filter_sub_category', None)
            filer_tag.append(filter['subcategory__title'])
        if request.GET.get('min_price_val'):
            filter['price__gte'] = request.GET.get('min_price_val', None)
            filer_tag.append(filter['price__gte'])
        if request.GET.get('max_price_val'):
            filter['price__lte'] = request.GET.get('max_price_val', None)
        if request.GET.get('min_weight_val'):
            filter_detail['weight__gte'] = request.GET.get('min_weight_val')
            filer_tag.append(filter_detail['weight__gte'])
        if request.GET.get('min_weight_val'):
            filter_detail['weight__lte'] = request.GET.get('max_weight_val')
        if request.GET.get('filter_size'):
            filter_detail['size'] = request.GET.get('filter_size')
            filer_tag.append(filter_detail['size'])
        if request.GET.get('filter_color'):
            filter_detail['color'] = request.GET.get('filter_color')
            filer_tag.append(filter_detail['color'])
        filter['filter_tag'] = filer_tag
        filter['filter_detail'] = filter_detail
        return filter


def cart_update(request, pk):
    """
       Add/Remove single product (possible multiple qty of product) to cart
       :param   request: Django's HTTP Request object,
                pk: Primary key of 
                    products to be added to cart
       :return: Success message
    """
    if request.method == 'GET':

        sess = request.session
        qty = request.GET.get('qty', False)
        if qty:
            # Initialize a cart and its qty in session if they don't exist
            sess['cart_qty'] = sess.get('cart_qty', 0) + int(qty)
            sess['cart'] = sess.get('cart', OrderedDict())

BestStore/FrontEnd/templates/Products/products.html
{% extends "General/base.html" %}
{% load static %}
{% block content %}
{% include 'Products/messages.html' %}
<body>
<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="{% url 'homepage' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">Products</li>
		</ol>
	</div>
</div>
</div>
<div class="products">
	<div class="container">
		<div class="col-md-4 products-left">
			<div class="categories animated wow slideInUp" data-wow-delay=".5s">
				<h3>Categories</h3>
				<ul class="cate">
					{% for cat in category %}
					<li><a class="filter_category" name="filter_category" href="/products/?filter_category={{ cat.category }}" value="{{ cat.category }}">{{ cat.category }}</a></li>
					<ul>
						{% for subcat in cat.subcategory_set.all %}
						<li><a class="filter_sub_category" name="filter_sub_category" href="/products/?filter_sub_category={{ subcat.title }}" value="{{ subcat.title }}">{{ subcat.title }}</a></li>
						{% endfor %}
					</ul>
					{% endfor %}
				</ul>
			</div>
			<form method="GET" action="{% url 'products' %}">
				<div class="filter-price animated wow slideInUp" data-wow-delay=".5s">
					{% if category_selected %}
					<input type="text" name="filter_category" value="{{ category_selected }}" hidden>
					{% endif %}
					{% if sub_category_selected %}
					<input type="text" name="filter_sub_category" value="{{ sub_category_selected }}" hidden>
					{% endif %}
					<h3>Filter By Price</h3>
					<ul class="dropdown-menu1" style="text-align: center">
						<div id="price_range" >
							<div class="dropdown" style="display: inline;">
								<label>$
									<input list="min_price_val" name="min_price_val" class="dropdown-value btn btn-default dropdown-toggle" style="width:120px"></label>
								<datalist data-toggle="dropdown" id="min_price_val">
									<option value="0" selected>
									<option value="100">
									<option value="1000">
									<option value="5000">
								</datalist>
							</div>
							<div class="dropdown" style="display: inline">
								<label> to $
									<input list="max_price_val" class="dropdown-value btn btn-default dropdown-toggle" name="max_price_val" style="width:120px"></label>
								<datalist data-toggle="dropdown" id="max_price_val">
									<option value="5001">
									<option value="10000">
									<option value="50000">
									<option value="100000" selected>
								</datalist>
							</div>
						</div>
					</ul>
				</div>
				<div class="categories animated wow slideInUp" data-wow-delay=".5s">
					<h3>Product Details</h3>
					<ul class="cate">
						{% if category_selected == "Cloth" %}
						<div class="dropdown" style="display: inline"><b>Size :</b>
							<input list="filter_size" class="dropdown-value btn btn-default dropdown-toggle" name="filter_size" style="width:120px"></label>
							<datalist data-toggle="dropdown"  id="filter_size">
                                <option value="Extra Small">Extra Small</option>

								<option value="Small">Small</option>
								<option value="Medium">Medium</option>
								<option value="Large">Large</option>
								<option value="Extra Large">Extra Large</option>
							</datalist>
						</div><br><br>
						{% endif %}
						<div class="dropdown" style="display: inline"><b>Color :</b>

							<input list="filter_color"  name="filter_color" class="dropdown-value btn btn-default dropdown-toggle" style="width:120px"></label>
							<datalist data-toggle="dropdown" id="filter_color">
                                <option value="Black" >Black</option>


								<option value="Blue">Blue</option>
								<option value="Red">Red</option>
								<option value="Green">Green</option>
								<option value="White">White</option>
								<option value="Rose Gold">Rose Gold</option>
								<option value="Grey">Grey</option>
							</datalist>
						</div><br><br>
						<div id="weight_range" >
							<div class="dropdown" style="display: inline;"><b>Weight :</b>
								<label>
									<input list="min_weight_val" class="dropdown-value btn btn-default dropdown-toggle" name="min_weight_val" style="width: 70px"> to</label>
								<datalist data-toggle="dropdown" id="min_weight_val">
									<option value="0">
									<option value="100">
									<option value="1000">
									<option value="5000">
								</datalist>
							</div>
							<div class="dropdown" style="display: inline">
								<label>
									<input list="max_weight_val" class="dropdown-value btn btn-default dropdown-toggle" name="max_weight_val" style="width: 70px">grams</label>
								<datalist data-toggle="dropdown" id="max_weight_val">
									<option value="100">
									<option value="1000">
									<option value="5001">
									<option value="10000">
									<option value="50000">
								</datalist>
							</div>
						</div>
				</div>
				<button class="btn btn-default align-right" type="submit" value="Filter">Filter</button>
		</div>
		</form>

	<div class="col-md-8 products-right">
        {% if message %}
        <div class="products-right-grids-bottom" style="text-align: center">
        <h1>{{ message }}</h1>
            </div>
        </div>
        {% else %}
		{% if filter_tags %}
    <div class="row" style="margin-top:0px;padding-top:30px;padding-left:15px">
        {% for tag in filter_tags %}
			{% if filter_tags.0 == tag %}
				<span class="btn" style="border: 1px solid #D8703F;background-color: white;color: #D8703F;padding: 10px 20px;font-size: 16px;cursor: pointer;border-radius: 5px;">{{tag}}
				</span>
			{% else %}
				<span class="btn" style="border: 1px solid red;background-color: white;color: red;padding: 10px 20px;font-size: 16px;cursor: pointer;border-radius: 5px;">{{tag}}
					<a href="" style="float:right;color:red" class="close-buttons" id="{{tag}}">&times;</a>
				</span>
			{% endif %}
		{% endfor %}
		<span class="btn" style="border: 1px solid red;background-color: white;color: red;padding: 10px 20px;font-size: 16px;cursor: pointer;border-radius: 5px;">Clear All
   		 <a href="" style="color:red" id="clear-all-btn" >&times;</a>
		</span>
		</div>
		{% else %}
		<div class="row" style="margin-top:0px">
		</div>
    {% endif %}

		<div class="products-right-grids-bottom">
			<div id="products_display">

				{% for prod in products %}
				<div class="col-md-4 products-right-grids-bottom-grid" style='margin-bottom: 8px; margin-top: 8px;'>
					<div class="new-collections-grid1 products-right-grid1 animated wow slideInUp" data-wow-delay=".5s">
						<div class="new-collections-grid1-image">
							<a href="single.html" class="product-image"><img src="{{prod.productimages_set.first.image.url}}" alt=" " height='170' width='200'></a>
							<div class="new-collections-grid1-image-pos products-right-grids-pos">
								<a href="/products/{{prod.slug}}/">Quick View</a>
							</div>
						</div>
						<h4><a href="single.html">{{prod.name}}</a></h4>
						<div class="simpleCart_shelfItem products-right-grid1-add-cart">
							<p style='text-align: center;'>${{prod.price}}<a data-pk="{{prod.id}}" data-price="{{prod.price}}" class="add-item" href="#">add to cart </a></p>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<div class="clearfix"> </div>
		</div>

		{% if products.has_other_pages %}
		<ul class="pagination">
			{% if products.has_previous %}
			<li><a href="?page={{ products.previous_page_number }}">&laquo;</a></li>
			{% else %}
			<li class="disabled"><span>&laquo;</span></li>
			{% endif %}
			{% for i in products.paginator.page_range %}
			{% if products.number == i %}
			<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
			{% else %}
			<li><a href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
			{% endfor %}
			{% if products.has_next %}
			<li><a href="?page={{ products.next_page_number }}">&raquo;</a></li>
			{% else %}
			<li class="disabled"><span>&raquo;</span></li>
			{% endif %}
		</ul>
		{% endif %}

		{% endif %}
	</div>
	<div class="clearfix"> </div>
</div>
</div>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"> </script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
<script>
		$('#clear-all-btn').click(function(event){
		event.preventDefault();
			old_url = window.location.href.split('&')[0];
			window.location.href = old_url;
		});
		$('.close-buttons').click(function(event)
		{
			result=[];
			event.preventDefault();
			filters = window.location.href.split('&');
			for (i=1;i<filters.length;i++)
			{
				filter_value = filters[i].split('=')[1];
				if(filter_value == this.id)
				{
			result = filters.filter(function(elem){
		    return elem != filters[i];
		});
				}
			}
			new_url = result.join('&');
			window.location.href = new_url;
		});
        $(document).ready(function(){
        	$(".filter_value").css('cursor', "pointer");
			$("#min_val, #max_val, .filter_value").click(function(){
				var filter_value = $(this).html();
				$.ajax({
					url: '/products/filter',
					data:{
						'min_value': $('#min_val option:selected').val(),
						'max_value': $('#max_val option:selected').val(),
						'filter_value': filter_value
					},
					method : 'GET',
					success: function(response) {
						$("#products_display").html(response);

					}
				});
			});
        });
</script>

{% include "General/footer.html" %}
{% endblock %}